export const PREVIOUS_SNAPSHOT = 'PREVIOUS_SNAPSHOT';
export const NEXT_SNAPSHOT = 'NEXT_SNAPSHOT';
export const STOP = 'STOP';
export const START = 'START';
export const SET_SNAPSHOTS = 'SET_SNAPSHOTS';
export const SET_HANDLER = 'SET_HANDLER';
export const SET_SPEED = 'SET_SPEED';
export const SET_PANEL_WIDTH_PARAMETERS = 'SET_PANEL_WIDTH_PARAMETERS';
